#!/bin/bash
#
# Copyright 2018 Red Hat, Inc.
#
# NAME
#     lab-console-admin - lab script for DO280-OCP4
#
# SYNOPSIS
#     lab-console-admin {start|finish}
#
#        start  - prepare the system for starting the lab
#        finish - perform post-lab finish
#
# DESCRIPTION
#     This script, based on singular argument, either does start or finish for
#     the [name of the exercise]
#
# CHANGELOG
#   * Fri Nov 26 2019 Joel Birchler <jbirchler@redhat.com>
#   - initial creation

PATH=/usr/bin:/bin:/usr/sbin:/sbin:/root/bin:/usr/local/bin
declare -a valid_commands=(start finish)

# Change these variables to match your exercise
this='console-admin'
title='Guided Exercise: Performing Cluster Administration'

# Do not change these variables
target='workstation'
run_as_root='true'


function lab_start {
  ocp4_print_prereq_header
  ocp4_is_cluster_up

  ocp4_print_setup_header
  ocp4_install_oc
  ocp4_add_standard_users
  ocp4_add_self_provisioing

  ocp4_print_setup_footer
}


function lab_finish {
  ocp4_print_cleanup_header
  ocp4_print_cleanup_footer
}



############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
